export enum Icon {
  Bat = "far fa-bat",
  Cat = "far fa-cat",
  Dog = "far fa-dog",
  Dragon = "far fa-dragon",
  Duck = "far fa-duck",
  Elephant = "far fa-elephant",
  Kiwi = "far fa-kiwi-bird",
  Monkey = "far fa-monkey",  
  Narwhal = "far fa-narwhal",
  Pegasus = "far fa-pegasus",
  Pig = "far fa-pig",
  Rabbit = "far fa-rabbit-fast",
  Rudolph = "far fa-deer-rudolph",
  Squirrel = "far fa-squirrel",
  Turtle = "far fa-turtle",

  OneGameDay = "fal fa-ticket-alt",
  FiveGameDays = "fal fa-sack",
  FourteenGameDays = "fal fa-box",
  TwentyEightGameDays = "fal fa-treasure-chest",
  OneHundredFourtyGameDays = "fal fa-parachute-box",

  NotificationRead = "fal fa-envelope-open",
  NotificationUnread = "fal fa-envelope",
  
  AppBrand = "fal fa-running",
  Dice = "fal fa-dice",
  Players = "fal fa-user-friends",
  Points = "fal fa-dice-d8",
  ProfileIcon = "profile-icon",
  Question = "fal fa-question",
  Steps = "fal fa-shoe-prints",  
  User = "fal fa-user",
  UserDeleted = "fal fa-user-slash",
  None = ""
}