export enum AppAction {  
  CloseModals = "Close Modals",
  CompleteAccountDeletion = "Complete Account Deletion",
  FailedAccountDeletion = "Failed Account Deletion",
  FailedStepTrackerConnection = "Failed Step Tracker Connection",
  InitiateAccountDeletion = "Initiate Account Deletion",
  InitiateSignOut = "Initiate Sign Out",
  InitiateStepTrackerConnection = "Initiate Step Tracker Connection",
  ResetStepTrackerConnection = "Reset Step Tracker Connection",
  SetGameDays = "Set Game Days",
  SetNotifications = "Set Notifications",
  SetNotificationsStatus = "Set Notifications Status",
  SetNotificationStats = "Set Notification Stats",
  SetProfile = "Set Profile",
  SetProfileAndClose = "Set Profile And Close",  
  SetStepTrackerConnectionStatus = "Set Step Tracker Connection Status",
  SetStatus = "Set Status",
  SignInUser = "Sign In User",
  SignInUserForFirstTime = "Sign In User For First Time",  
  ToggleAcceptInvite = "Toggle Accept Invite",
  ToggleDeleteAccount = "Toggle Delete Account",
  ToggleUpdateProfile = "Toggle Update Profile",
  ToggleMenu = "Toggle Menu",
  ToggleSignIn = "Toggle Sign In"
}