export enum AppAction {  
  CloseModals = "Close Modals",
  CompleteAccountDeletion = "Complete Account Deletion",
  FailedAccountDeletion = "Failed Account Deletion",
  FailedStepTrackerConnection = "Failed Step Tracker Connection",
  InitiateAccountDeletion = "Initiate Account Deletion",
  InitiateSignOut = "Initiate Sign Out",
  InitiateStepTrackerConnection = "Initiate Step Tracker Connection",
  ResetStepTrackerConnection = "Reset Step Tracker Connection",
  SetCookieStatus = "Set Cookie Status",
  SetNotificationStats = "Set Notification Stats",
  SetProfile = "Set Profile",
  SetStepTrackerConnectionStatus = "Set Step Tracker Connection Status",
  SetStatus = "Set Status",
  SignInUser = "Sign In User",
  ToggleAcceptInvite = "Toggle Accept Invite",
  ToggleCookieBanner = "Toggle Cookie Banner",
  ToggleDeleteAccount = "Toggle Delete Account",  
  ToggleHideFooter = "Toggle Hide Footer",
  ToggleHowToPlay = "Toggle How To Play",  
  ToggleUpdateProfile = "Toggle Update Profile",
  ToggleMenu = "Toggle Menu",
  ToggleSignIn = "Toggle Sign In"
}